development:
  adapter: sqlite3
  database: db/job_portal_development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/job_portal_test.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: db/job_portal_production.sqlite3
  pool: 5
  timeout: 5000